//
//  String+Localization.swift
//  POS
//
//  Created by Việt Anh Nguyễn on 16/4/25.
//

import Foundation

final class AppLocalizedString {
    let displayNamePlaceholder = NSLocalizedString("display_name_placeholder", comment: "")
    let addItem = NSLocalizedString("add_item", comment: "")
    let cancel = NSLocalizedString("cancel", comment: "")
    let cashierRole = NSLocalizedString("cashier_role", comment: "")
    let createNewOrder = NSLocalizedString("create_new_order", comment: "")
    let daily = NSLocalizedString("daily", comment: "")
    let deleteItem = NSLocalizedString("delete_item", comment: "")
    let dontHaveAnAccount = NSLocalizedString("dont_have_an_account", comment: "")
    let editItem = NSLocalizedString("edit_item", comment: "")
    let emailPlaceholder = NSLocalizedString("email_placeholder", comment: "")
    let firestoreErrorUnknown = NSLocalizedString("error.firestorage.unknown", comment: "")
    let firestoreErrorDecoding = NSLocalizedString("error.firestore.decoding", comment: "")
    let firestoreErrorNotFound = NSLocalizedString("error.firestore.not_found", comment: "")
    let firestoreErrorPermission = NSLocalizedString("error.firestore.permission", comment: "")
    let functionsErrorInternal = NSLocalizedString("error.functions.internal", comment: "")
    let functionsErrorInvalidArgument = NSLocalizedString("error.functions.invalid_argument", comment: "")
    let functionsErrorTimeOut = NSLocalizedString("error.functions.timeout", comment: "")
    let functionsErrorUnknown = NSLocalizedString("error.functions.unknown", comment: "")
    let messagingErrorPermission = NSLocalizedString("error.messaging.permisson", comment: "")
    let messagingErrorTokenFailed = NSLocalizedString("error.messaging.token_failed", comment: "")
    let messagingErrorUnknown = NSLocalizedString("error.messaging.unknown", comment: "")
    let errorNetwork = NSLocalizedString("error.network", comment: "")
    let storageErrorPermission = NSLocalizedString("error.storage.permission", comment: "")
    let storageErrorUnknown = NSLocalizedString("error.storage.unknown", comment: "")
    let storageErrorUploadFailed = NSLocalizedString("error.storage.upload_failed", comment: "")
    let storageErrorDownloadFailed = NSLocalizedString("error.storage.download_failed", comment: "")
    let storageErrorFileNotFound = NSLocalizedString("error.storage.file_not_found", comment: "")
    let errorUnknown = NSLocalizedString("error.unknown", comment: "")
    let inventory = NSLocalizedString("inventory", comment: "")
    let itemName = NSLocalizedString("item_name", comment: "")
    let itemPrice = NSLocalizedString("item_price", comment: "")
    let login = NSLocalizedString("login", comment: "")
    let loginFailed = NSLocalizedString("login_failed", comment: "")
    let logout = NSLocalizedString("logout", comment: "")
    let measureGram = NSLocalizedString("measure.gram", comment: "")
    let measureKilogram = NSLocalizedString("measure.kilogram", comment: "")
    let measureLiter = NSLocalizedString("measure.liter", comment: "")
    let measureMilliliter = NSLocalizedString("measure.milliliter", comment: "")
    let measurePiece = NSLocalizedString("measure.piece", comment: "")
    let menuManagement = NSLocalizedString("menu_management", comment: "")
    let monthly = NSLocalizedString("monthly", comment: "")
    let newOrder = NSLocalizedString("new_order", comment: "")
    let no = NSLocalizedString("no", comment: "")
    let ok = NSLocalizedString("ok", comment: "")
    let orderFailed = NSLocalizedString("order_failed", comment: "")
    let orderSuccess = NSLocalizedString("order_success", comment: "")
    let ownerRole = NSLocalizedString("owner_role", comment: "")
    let passwordPlaceholder = NSLocalizedString("password_placeholder", comment: "")
    let permissionDenied = NSLocalizedString("permission_denied", comment: "")
    let printReceipt = NSLocalizedString("print_receipt", comment: "")
    let printConnected = NSLocalizedString("printer_connected", comment: "")
    let printDisconnected = NSLocalizedString("printer_disconnected", comment: "")
    let printing = NSLocalizedString("printing", comment: "")
    let revenueReport = NSLocalizedString("revenue_report", comment: "")
    let sendReport = NSLocalizedString("send_report", comment: "")
    let shopNamePlaceholder = NSLocalizedString("shop_name_placeholder", comment: "")
    let signUp = NSLocalizedString("signup", comment: "")
    let staffManagement = NSLocalizedString("staff_management", comment: "")
    let stockUpdated = NSLocalizedString("stock_updated", comment: "")
    let total = NSLocalizedString("total", comment: "")
    let warningLowStock = NSLocalizedString("warning_low_stock", comment: "")
    let weekly = NSLocalizedString("weekly", comment: "")
    let yes = NSLocalizedString("yes", comment: "")
    let reEnterPasswordPlaceholder = NSLocalizedString("re_enter_password_placeholder", comment: "")
    let signUpNow = NSLocalizedString("signup_now", comment: "")
    let alreadyHaveAnAccount = NSLocalizedString("already_have_an_account", comment: "")
    let forgotPassword = NSLocalizedString("forgot_password", comment: "")
    let forgotPasswordContent = NSLocalizedString("forgot_password_content", comment: "")
    let createNewShop = NSLocalizedString("create_new_shop", comment: "")
    let hintShopName = NSLocalizedString("hint.shop.name_format", comment: "")
    let verifyEmailSentContent = NSLocalizedString("verify_email_sent_content", comment: "")
}
