//
//  String+Localization.swift
//  POS
//
//  Created by Việt Anh Nguyễn on 16/4/25.
//

import Foundation

final class AppLocalizedString {
    static let displayNamePlaceholder = NSLocalizedString("display_name_placeholder", comment: "")
    static let addItem = NSLocalizedString("add_item", comment: "")
    static let cancel = NSLocalizedString("cancel", comment: "")
    static let cashierRole = NSLocalizedString("cashier_role", comment: "")
    static let createNewOrder = NSLocalizedString("create_new_order", comment: "")
    static let daily = NSLocalizedString("daily", comment: "")
    static let deleteItem = NSLocalizedString("delete_item", comment: "")
    static let dontHaveAnAccount = NSLocalizedString("dont_have_an_account", comment: "")
    static let editItem = NSLocalizedString("edit_item", comment: "")
    static let emailPlaceholder = NSLocalizedString("email_placeholder", comment: "")
    static let firestoreErrorUnknown = NSLocalizedString("error.firestorage.unknown", comment: "")
    static let firestoreErrorDecoding = NSLocalizedString("error.firestore.decoding", comment: "")
    static let firestoreErrorNotFound = NSLocalizedString("error.firestore.not_found", comment: "")
    static let firestoreErrorPermission = NSLocalizedString("error.firestore.permission", comment: "")
    static let functionsErrorInternal = NSLocalizedString("error.functions.internal", comment: "")
    static let functionsErrorInvalidArgument = NSLocalizedString("error.functions.invalid_argument", comment: "")
    static let functionsErrorTimeOut = NSLocalizedString("error.functions.timeout", comment: "")
    static let functionsErrorUnknown = NSLocalizedString("error.functions.unknown", comment: "")
    static let messagingErrorPermission = NSLocalizedString("error.messaging.permisson", comment: "")
    static let messagingErrorTokenFailed = NSLocalizedString("error.messaging.token_failed", comment: "")
    static let messagingErrorUnknown = NSLocalizedString("error.messaging.unknown", comment: "")
    static let errorNetwork = NSLocalizedString("error.network", comment: "")
    static let storageErrorPermission = NSLocalizedString("error.storage.permission", comment: "")
    static let storageErrorUnknown = NSLocalizedString("error.storage.unknown", comment: "")
    static let storageErrorUploadFailed = NSLocalizedString("error.storage.upload_failed", comment: "")
    static let storageErrorDownloadFailed = NSLocalizedString("error.storage.download_failed", comment: "")
    static let storageErrorFileNotFound = NSLocalizedString("error.storage.file_not_found", comment: "")
    static let errorUnknown = NSLocalizedString("error.unknown", comment: "")
    static let inventory = NSLocalizedString("inventory", comment: "")
    static let itemName = NSLocalizedString("item_name", comment: "")
    static let itemPrice = NSLocalizedString("item_price", comment: "")
    static let login = NSLocalizedString("login", comment: "")
    static let loginFailed = NSLocalizedString("login_failed", comment: "")
    static let logout = NSLocalizedString("logout", comment: "")
    static let measureGram = NSLocalizedString("measure.gram", comment: "")
    static let measureKilogram = NSLocalizedString("measure.kilogram", comment: "")
    static let measureLiter = NSLocalizedString("measure.liter", comment: "")
    static let measureMilliliter = NSLocalizedString("measure.milliliter", comment: "")
    static let measurePiece = NSLocalizedString("measure.piece", comment: "")
    static let menuManagement = NSLocalizedString("menu_management", comment: "")
    static let monthly = NSLocalizedString("monthly", comment: "")
    static let newOrder = NSLocalizedString("new_order", comment: "")
    static let no = NSLocalizedString("no", comment: "")
    static let ok = NSLocalizedString("ok", comment: "")
    static let orderFailed = NSLocalizedString("order_failed", comment: "")
    static let orderSuccess = NSLocalizedString("order_success", comment: "")
    static let ownerRole = NSLocalizedString("owner_role", comment: "")
    static let passwordPlaceholder = NSLocalizedString("password_placeholder", comment: "") 
    static let permissionDenied = NSLocalizedString("permission_denied", comment: "")
    static let printReceipt = NSLocalizedString("print_receipt", comment: "")
    static let printConnected = NSLocalizedString("printer_connected", comment: "")
    static let printDisconnected = NSLocalizedString("printer_disconnected", comment: "")
    static let printing = NSLocalizedString("printing", comment: "")
    static let revenueReport = NSLocalizedString("revenue_report", comment: "")
    static let sendReport = NSLocalizedString("send_report", comment: "")
    static let shopNamePlaceholder = NSLocalizedString("shop_name_placeholder", comment: "")
    static let signUp = NSLocalizedString("signup", comment: "")
    static let staffManagement = NSLocalizedString("staff_management", comment: "")
    static let stockUpdated = NSLocalizedString("stock_updated", comment: "")
    static let total = NSLocalizedString("total", comment: "")
    static let warningLowStock = NSLocalizedString("warning_low_stock", comment: "")
    static let weekly = NSLocalizedString("weekly", comment: "")
    static let yes = NSLocalizedString("yes", comment: "")
    static let reEnterPasswordPlaceholder = NSLocalizedString("re_enter_password_placeholder", comment: "")
    static let signUpNow = NSLocalizedString("signup_now", comment: "")
    static let alreadyHaveAnAccount = NSLocalizedString("already_have_an_account", comment: "")
    static let forgotPassword = NSLocalizedString("forgot_password", comment: "")
    static let forgotPasswordContent = NSLocalizedString("forgot_password_content", comment: "")
    static let createNewShop = NSLocalizedString("create_new_shop", comment: "")
    static let hintShopName = NSLocalizedString("hint.shop.name_format", comment: "")
    static let verifyEmailSentContent = NSLocalizedString("verify_email_sent_content", comment: "")
}
